### ISSUE TITLE
Add an appropriate favicon

### ISSUE THREAD

**Issue by m2mathew** [reactjs-dallas/reactjs-dallas-site#1]
Right now we have the stock Gatsby one. It's gorgeous, but let's make this personal. 🤓 

### Ideas

- React atom but deep purple
- Something to do with Dallas
- The shape of Texas but with some React flair

**Comment by Qfist** [comment]
How about:
1. Cut out the top of the Reunion Tower and take the globe part. Ideally the one with lights on.
2. Vectorize the globe and simplify it to just be that round light grid.
3. Change the color to deep purple or whatever you prefer
4. Cut out the star shape in the middle. - Seems to be one of Dallas symbols :)
5. Place reactor icon or a nuclear cooling tower icon inside the star.
5.1 If you want to go overboard and create a actual logo you can even use text somewhere along the way :)

**Comment by m2mathew** [comment]
Good stuff. I wonder if a favicon would be too small for that much detail. Maybe just a star that has the electron orbit rings would be right?

I dig the Reunion Tower idea. I think that would be more appropriate for an outright logo...though I could be convinced otherwise.

**Comment by Qfist** [comment]
Yeah, of course , i had some extra inspiration and i had to share it. :) 
I am sure if you like it you can build up / down on that idea and make a favicon. 
I might give the logo thing a shot during the next week.

**Comment by m2mathew** [comment]
Shawn Rhodes from the DFW community made a little something for us.

![react-dallas-logo](https://user-images.githubusercontent.com/11624407/46258988-35b61a80-c498-11e8-9c21-3698e5db5d7d.png)


You can see it in our WIP [ReactJS Dallas website](https://reactjs-dallas-website.netlify.com/), too.

**Comment by m2mathew** [comment]
I will leave this issue open in case there is feedback about the logo or someone from the community has some alternatives that require debate. 🤓

**Comment by Qfist** [comment]
Hey , that's nice. I got overwhelmed with work and completely forgot about this. I am glad someone took a shot at it. Well done :)

**Comment by incorelabs** [comment]
The logo looks great.. :D

**Comment by m2mathew** [comment]
Closing this since we have a logo and favicon. 🕺
