### ISSUE TITLE
add link to actual website 🙈

### ISSUE THREAD

**Issue by ipatch** [reactjs-dallas/reactjs-dallas-site#12]
Maybe I'm getting blinder 🦇 in my old age 👵 but I didn't notice a single link on this repo to the actual website that is repo powers, ie. if someone visits this repo and just wants browse, ie. see what the actual website looks like **there's no link**.

That said, github offers a pretty neat little field for adding a link to a `http(s)://` address at the top of the repo.  Think it would be beneficial for people who would like to visit the site after browsing through the source. I was unable to locate the site for this repo until I received an email from meetup which had the below link

[reactjsdallas.com](https://www.reactjsdallas.com/)

And doing a search for `react js dallas` in google

```
https://www.google.com/search?q=react%20js%20dallas
```

doesn't even list the above address in the results. 🤷‍♂️

Also **package.json** files support various meta data fields for such things as web addresses.

cheers 🍻

**Comment by m2mathew** [comment]
@ipatch Thanks, Chris! I have been hoping for people to jump in and correct several of the issues here. We need the help from both the young and the old!

We need to SEO this site up, too. I will open a separate issue for us to get this site all meta.

**Comment by ipatch** [comment]
![confused](https://i.imgur.com/bwXe84z.jpg)
